name: kami_delivery
description: "App de Delivery KamiKami - Projeto Full Stack"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Comunicação com o servidor Python
  http: ^1.1.0 

  # Localização para cálculo de frete por KM
  geolocator: ^10.1.0

  # Integração para enviar pedidos via WhatsApp
  url_launcher: ^6.2.5

  # Ícones padrão para iOS
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.14.0
  google_places_flutter: ^2.1.1
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Aqui você poderá adicionar logo do restaurante no futuro
  # assets:
  #   - assets/logo.png