name: kami_delivery
description: "App de Delivery KamiKami - Projeto Full Stack"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ComunicaÃ§Ã£o com o servidor Python e Mercado Pago
  http: ^1.1.0 

  # LocalizaÃ§Ã£o para cÃ¡lculo de frete
  geolocator: ^10.1.0

  # IntegraÃ§Ã£o para links externos e WhatsApp
  url_launcher: ^6.2.5

  # Ãcones padrÃ£o
  cupertino_icons: ^1.0.8

  # PACOTES DE MAPA (VersÃµes estÃ¡veis para Web)
  google_maps_flutter: ^2.5.0
  google_places_flutter: ^2.0.8
  location: ^5.0.3

  # ðŸ”¥ FIREBASE
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true